common: &common
  dev_key: AIzaSyDQpOQfxbtmGg5xR84UmEM0J-Ji5e-6a80
  username:  sclaudinodaffara@gmail.com
  password:  Ankrvideo
  
test:
  <<: *common
development:
  <<: *common
production:
  <<: *common
